### ISSUE TITLE
Installing (using cabal) of MonadRandom for profiling fails

### ISSUE THREAD

**Issue by pjljvandelaar** [byorgey/MonadRandom#21] opened 2016-04-08 12:26 UTC
cabal install -p MonadRandom --reinstall 
fails on windows (both in dos cmd and Cygwin window)

Relevant info on windows:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

c:\TorXakisSandbox\1745_core_test_fabla\torxakis>cabal install -p MonadRandom --reinstall
Resolving dependencies...
Configuring MonadRandom-0.4.2.2...
Building MonadRandom-0.4.2.2...
Preprocessing library MonadRandom-0.4.2.2...
[1 of 2] Compiling Control.Monad.Random.Class ( Control\Monad\Random\Class.hs, dist\build\Co
ntrol\Monad\Random\Class.o )
[2 of 2] Compiling Control.Monad.Random ( Control\Monad\Random.hs, dist\build\Control\Monad\
Random.o )

Control\Monad\Random.hs:63:18:
    Could not find module `Control.Monad.Trans.Except'
    Perhaps you haven't installed the profiling libraries for package `transformers-compat-0
.4.0.4'?
    Use -v to see a list of the files searched for.
Failed to install MonadRandom-0.4.2.2
cabal: Error: some packages failed to install:
MonadRandom-0.4.2.2 failed during the building phase. The exception was:
ExitFailure 1

Note: the suggestion is incorrect:
c:\TorXakisSandbox\1745_core_test_fabla\torxakis>cabal install -p transformers-compat --rein
stall
Resolving dependencies...
In order, the following will be installed:
transformers-compat-0.5.1.4 (reinstall)
Warning: Note that reinstalls are always dangerous. Continuing anyway...
Configuring transformers-compat-0.5.1.4...
Building transformers-compat-0.5.1.4...
Preprocessing library transformers-compat-0.5.1.4...
[1 of 2] Compiling Paths_transformers_compat ( dist\build\autogen\Paths_transformers_compat.
hs, dist\build\Paths_transformers_compat.o )
[2 of 2] Compiling Control.Monad.Trans.Instances ( src\Control\Monad\Trans\Instances.hs, dis
t\build\Control\Monad\Trans\Instances.o )
[1 of 2] Compiling Paths_transformers_compat ( dist\build\autogen\Paths_transformers_compat.
hs, dist\build\Paths_transformers_compat.p_o )
[2 of 2] Compiling Control.Monad.Trans.Instances ( src\Control\Monad\Trans\Instances.hs, dis
t\build\Control\Monad\Trans\Instances.p_o )
In-place registering transformers-compat-0.5.1.4...
Installing library in
C:\Users\laarpjljvd\AppData\Roaming\cabal\transformers-compat-0.5.1.4\ghc-7.6.3
Registering transformers-compat-0.5.1.4...
Installed transformers-compat-0.5.1.4

c:\TorXakisSandbox\1745_core_test_fabla\torxakis>cabal install -p MonadRandom --reinstall
Resolving dependencies...
Configuring MonadRandom-0.4.2.2...
Building MonadRandom-0.4.2.2...
Preprocessing library MonadRandom-0.4.2.2...
[1 of 2] Compiling Control.Monad.Random.Class ( Control\Monad\Random\Class.hs, dist\build\Co
ntrol\Monad\Random\Class.o )
[2 of 2] Compiling Control.Monad.Random ( Control\Monad\Random.hs, dist\build\Control\Monad\
Random.o )

Control\Monad\Random.hs:63:18:
    Could not find module `Control.Monad.Trans.Except'
    Perhaps you haven't installed the profiling libraries for package `transformers-compat-0
.4.0.4'?
    Use -v to see a list of the files searched for.
Failed to install MonadRandom-0.4.2.2
cabal: Error: some packages failed to install:
MonadRandom-0.4.2.2 failed during the building phase. The exception was:
ExitFailure 1

And using cygwin I get exactly the same error:

laarpjljvd@PC-14419 /cygdrive/c/TorXakisSandbox/1745_core_test_fabla/torxakis/sys
$ cabal install -p MonadRandom --reinstall
Resolving dependencies...
Configuring MonadRandom-0.4.2.2...
Building MonadRandom-0.4.2.2...
Preprocessing library MonadRandom-0.4.2.2...
[1 of 2] Compiling Control.Monad.Random.Class ( Control\Monad\Random\Class.hs, dist\build\Control\Monad\Random\Class.o )
[2 of 2] Compiling Control.Monad.Random ( Control\Monad\Random.hs, dist\build\Control\Monad\Random.o )

Control\Monad\Random.hs:63:18:
    Could not find module `Control.Monad.Trans.Except'
    Perhaps you haven't installed the profiling libraries for package `transformers-compat-0.4.0.4'?
    Use -v to see a list of the files searched for.
Failed to install MonadRandom-0.4.2.2
cabal.exe: Error: some packages failed to install:
MonadRandom-0.4.2.2 failed during the building phase. The exception was:
ExitFailure 1

Also in this case the suggestion seems incorrect:

laarpjljvd@PC-14419 /cygdrive/c/TorXakisSandbox/1745_core_test_fabla/torxakis/sys
$ cabal install -p transformers-compat --reinstall
Resolving dependencies...
In order, the following will be installed:
transformers-compat-0.5.1.4 (reinstall)
Warning: Note that reinstalls are always dangerous. Continuing anyway...
Configuring transformers-compat-0.5.1.4...
Building transformers-compat-0.5.1.4...
Preprocessing library transformers-compat-0.5.1.4...
[1 of 2] Compiling Paths_transformers_compat ( dist\build\autogen\Paths_transformers_compat.hs, dist\build\Paths_transformers_compat.o )
[2 of 2] Compiling Control.Monad.Trans.Instances ( src\Control\Monad\Trans\Instances.hs, dist\build\Control\Monad\Trans\Instances.o )
[1 of 2] Compiling Paths_transformers_compat ( dist\build\autogen\Paths_transformers_compat.hs, dist\build\Paths_transformers_compat.p_o )
[2 of 2] Compiling Control.Monad.Trans.Instances ( src\Control\Monad\Trans\Instances.hs, dist\build\Control\Monad\Trans\Instances.p_o )
In-place registering transformers-compat-0.5.1.4...
Installing library in
C:\Users\laarpjljvd\AppData\Roaming\cabal\transformers-compat-0.5.1.4\ghc-7.6.3
Registering transformers-compat-0.5.1.4...
Installed transformers-compat-0.5.1.4

laarpjljvd@PC-14419 /cygdrive/c/TorXakisSandbox/1745_core_test_fabla/torxakis/sys
$ cabal install -p MonadRandom --reinstall
Resolving dependencies...
Configuring MonadRandom-0.4.2.2...
Building MonadRandom-0.4.2.2...
Preprocessing library MonadRandom-0.4.2.2...
[1 of 2] Compiling Control.Monad.Random.Class ( Control\Monad\Random\Class.hs, dist\build\Control\Monad\Random\Class.o )
[2 of 2] Compiling Control.Monad.Random ( Control\Monad\Random.hs, dist\build\Control\Monad\Random.o )

Control\Monad\Random.hs:63:18:
    Could not find module `Control.Monad.Trans.Except'
    Perhaps you haven't installed the profiling libraries for package `transformers-compat-0.4.0.4'?
    Use -v to see a list of the files searched for.
Failed to install MonadRandom-0.4.2.2
cabal.exe: Error: some packages failed to install:
MonadRandom-0.4.2.2 failed during the building phase. The exception was:
ExitFailure 1

**Comment by pjljvandelaar** [comment] 2016-04-08 13:33
some additional info
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3

-------------------------------------------------------------------------------------------
$ cabal --version
cabal-install version 1.16.0.2
using version 1.16.0 of the Cabal library

--------------------------------------------------------------------------------------------------
$ cabal info MonadRandom
* MonadRandom      (library)
    Synopsis:      Random-number generation monad.
    Versions available: 0.2.0.1, 0.3, 0.3.0.1, 0.3.0.2, 0.4, 0.4.1, 0.4.2,
                        0.4.2.1, 0.4.2.2 (and 15 others)
    Versions installed: 0.3.0.2
    Homepage:      [ Not specified ]
    Bug reports:   https://github.com/byorgey/MonadRandom/issues
    Description:   Support for computations which consume random values.
    Category:      Control
    License:       OtherLicense
    Author:        Cale Gibbard and others
    Maintainer:    Brent Yorgey <byorgey@gmail.com>
    Source repo:   git://github.com/byorgey/MonadRandom.git
    Dependencies:  base >=2 && <5, transformers >=0.3 && <0.6,
                   transformers-compat >=0.4 && <0.6, mtl >=2.1 && <2.3,
                   random -any
    Documentation: [ Not installed ]
    Cached:        Yes
    Modules:
        Control.Monad.Random
        Control.Monad.Random.Class


------------------------------------------------------------------------------------------------
$ cabal info transformers-compat
* transformers-compat (library)
    Synopsis:      A small compatibility shim exposing the new types from
                   transformers 0.3 and 0.4 to older Haskell platforms.
    Versions available: 0.3.3.4, 0.4.0.3, 0.4.0.4, 0.5.0.2, 0.5.0.3, 0.5.0.4,
                        0.5.1.2, 0.5.1.3, 0.5.1.4 (and 10 others)
    Versions installed: 0.4.0.4, 0.5.1.4
    Homepage:      http://github.com/ekmett/transformers-compat/
    Bug reports:   http://github.com/ekmett/transformers-compat/issues
    Description:   This package includes backported versions of types that were
                   added to transformers in transformers 0.3, 0.4, and 0.5 for
                   users who need strict transformers 0.2 or 0.3 compatibility
                   to run on old versions of the platform, but also need those
                   types.

                   Those users should be able to just depend on @transformers >=
                   0.2@ and @transformers-compat >= 0.3@.

                   Note: missing methods are not supplied, but this at least
                   permits the types to be used.
    Category:      Compatibility
    License:       BSD3
    Author:        Edward A. Kmett
    Maintainer:    Edward A. Kmett <ekmett@gmail.com>
    Source repo:   git://github.com/ekmett/transformers-compat.git
    Flags:         two, three, mtl
    Dependencies:  base >=4.3 && <5, transformers ==0.3.*, mtl ==2.1.*,
                   transformers ==0.2.*, mtl ==2.0.*,
                   transformers >=0.4.1 && <0.6, ghc-prim -any
    Documentation: [ Not installed ]
    Cached:        Yes
    Modules:
        Control.Monad.Trans.Instances

**Comment by pjljvandelaar** [comment] 2016-04-08 14:06
Control.Monad.Trans.Except is part of transformers:http://hackage.haskell.org/package/transformers-0.5.1.0/docs/Control-Monad-Trans-Except.html
NOT transformers-compat as the feedback states: "Perhaps you haven't installed the profiling libraries for package transformers-compat"

info on transformers:
$ cabal info transformers
* transformers     (library)
    Synopsis:      Concrete functor and monad transformers
    Versions available: 0.2.2.1, 0.3.0.0, 0.4.1.0, 0.4.2.0, 0.4.3.0, 0.5.0.1,
                        0.5.0.2, 0.5.1.0, 0.5.2.0 (and 12 others)
    Versions installed: 0.3.0.0, 0.5.2.0
    Homepage:      [ Not specified ]
    Bug reports:   http://hub.darcs.net/ross/transformers/issues
    Description:   A portable library of functor and monad transformers,
                   inspired by the paper \"Functional Programming with
                   Overloading and Higher-Order Polymorphism\", by Mark P Jones,
                   in /Advanced School of Functional Programming/, 1995
                   (<http://web.cecs.pdx.edu/~mpj/pubs/springschool.html>).

                   This package contains:

                   * the monad transformer class (in
                   "Control.Monad.Trans.Class") and IO monad class (in
                   "Control.Monad.IO.Class")

                   * concrete functor and monad transformers, each with
                   associated operations and functions to lift operations
                   associated with other transformers.

                   The package can be used on its own in portable Haskell code,
                   in which case operations need to be manually lifted through
                   transformer stacks (see "Control.Monad.Trans.Class" for some
                   examples). Alternatively, it can be used with the
                   non-portable monad classes in the @mtl@ or @monads-tf@
                   packages, which automatically lift operations introduced by
                   monad transformers through other transformers.
    Category:      Control
    License:       BSD3
    Author:        Andy Gill, Ross Paterson
    Maintainer:    Ross Paterson <R.Paterson@city.ac.uk>
    Source repo:   http://hub.darcs.net/ross/transformers
    Dependencies:  base >=2 && <6, ghc-prim -any
    Documentation: [ Not installed ]
    Cached:        Yes
    Modules:
        Control.Applicative.Backwards
        Control.Applicative.Lift
        Control.Monad.IO.Class
        Control.Monad.Signatures
        Control.Monad.Trans.Class
        Control.Monad.Trans.Cont
        Control.Monad.Trans.Error
        Control.Monad.Trans.Except
        Control.Monad.Trans.Identity
        Control.Monad.Trans.List
        Control.Monad.Trans.Maybe
        Control.Monad.Trans.RWS
        Control.Monad.Trans.RWS.Lazy
        Control.Monad.Trans.RWS.Strict
        Control.Monad.Trans.Reader
        Control.Monad.Trans.State
        Control.Monad.Trans.State.Lazy
        Control.Monad.Trans.State.Strict
        Control.Monad.Trans.Writer
        Control.Monad.Trans.Writer.Lazy
        Control.Monad.Trans.Writer.Strict
        Data.Functor.Classes
        Data.Functor.Compose
        Data.Functor.Constant
        Data.Functor.Identity
        Data.Functor.Product
        Data.Functor.Reverse
        Data.Functor.Sum

**Comment by byorgey** [comment] 2016-04-08 15:14
`Control.Monad.Trans.Except` is exported by *both* `transformers` and `transformers-compat`.  The problem is that the build of `MonadRandom` specifically wants `transformers-compat-0.4.0.4`, and when you install the profiling version of `transformers-compat` it is installing the latest version, 0.5.1.4.  Try doing `cabal install -p transformers-compat-0.4.0.4 --reinstall`.

Closing this ticket since it is not a problem with `MonadRandom`, but feel free to comment if you are still having trouble getting it to work.

**Closed by byorgey** 2016-04-08 15:14 UTC
